version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Updating system packages..."
      - yum install -y amazon-linux-extras
      - amazon-linux-extras enable mariadb10.5
      - yum clean metadata
      - echo "Installing dependencies..."
      - yum install -y mariadb-devel gcc python3-devel libffi-devel
  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t ./python/lib/python3.9/site-packages
  build:
    commands:
      - echo "Creating deployment package..."
      - zip -r deployment-package.zip lambda_function.py
      - zip -r deployment-package.zip ./python/lib/python3.9/site-packages/*
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - deployment-package.zip
