version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - dnf install -y pip
      - dnf install -y mariadb105-devel gcc python3-devel libffi-devel
  pre_build:
    commands:
      - echo "Installing Python dependencies from requirements.txt..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Creating deployment package..."
      - zip -r deployment-package.zip lambda_function.py
      - zip -r deployment-package.zip . -x '.env' -x '.db' -x '.github/**' -x '.git/**' -x 'static/**' -x 'cache/**' -x 'pytest_cache/**' -x 'node_modules/**' -x '**/tests/**' -x '**sqlite3**' -x '**.pdf' -x '**.ppt' -x '**.doc' -x '**.docx' -x '**.zip' -x '**/__pycache__/**'
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - deployment-package.zip
